### ISSUE TITLE
Void Fiend Sprinting Sound

### ISSUE THREAD

**Issue by myd3boro** [tlsJP/ror2-av-effect-options#4]
Void Fiend's sprinting sound is quite loud, and becomes irritating since you constantly toggle between sprinting and walking. 

Reducing the volume would be very nice!

**Comment by tlsJP** [comment]
I'll try to look into it. Currently trying to find the audio for void fiend's jump actually.

**Comment by myd3boro** [comment]
I believe his jumping and sprinting sound is the same.

**Comment by tlsJP** [comment]
Fixed in v1.13.6
